@host = http://localhost:3000
@urlclientes =/api/cliente

@urlHotel=/api/hotel

@urlViaje =/api/viaje

############################################
############################################
##############  Api cliente  ###############

#####peticion todos los clientes####
GET {{host}}{{urlclientes}}
####peticion insertar cliente####
POST {{host}}{{urlclientes}}
Content-Type: application/json

{
    "nombre": "Juan ",
    "apellidos": "Dominguez",
    "direccion": "Calle la vida es muy dura 5",
    "telefono": 666551,
    "fecha_de_nacimiento":"1988-02-02",
    "email": "lkljsss@gmail.com",
    "dni": "25212545s"
  }
#########

POST {{host}}{{urlclientes}}
Content-Type: application/json

{
    "nombre": "pedro ",
    "apellidos": "Dominguez",
     "direccion": "calle quevedo 12",
     "telefono": 6635544,
     "fecha_de_nacimiento":"2002-01-10",
     "email": "lkljassss@gmail.com",
     "dni": "25212575s"


    


    

  }
#############muestra un ID####
GET {{host}}{{urlclientes}}/1

##########borra un cliente por id####
DELETE {{host}}{{urlclientes}}/4

############################################
############################################
##############  Api Hoteles  ###############

####devuelve los hoteles####
GET {{host}}{{urlHotel}}

#####inserta un hotel####
POST {{host}}{{urlHotel}}
Content-Type: application/json

  {
    "nombre": "melia",
    "direccion": "lirio 125",
    "ciudad":"valencia",
    "numero_de_estrellas": 5,
    "descripcion":"hotel primera linea",
    "tarifa":"B1"

  }

##########borra un hotel por id#####
DELETE  {{host}}{{urlHotel}}/4  



