@host = http://localhost:3000
@urlclientes =/api/cliente

@urlHotel=/api/hotel

@urlViaje =/api/viaje

############################################
############################################
##############  Api cliente  ###############

#####peticion todos los clientes####
GET {{host}}{{urlclientes}}
####peticion insertar cliente####
POST {{host}}{{urlclientes}}
Content-Type: application/json

{
    "nombre": "Juan ",
    "apellidos": "Dominguez",
    "direccion": "Calle la vida es muy dura 5",
    "telefono": 666551,
    "fecha_de_nacimiento":"1988-02-02",
    "email": "lkljsss@gmail.com",
    "dni": "25212545s"
  }
#########

POST {{host}}{{urlclientes}}
Content-Type: application/json

{
    "nombre": "pedro ",
    "apellidos": "Dominguez",
     "direccion": "calle quevedo 12",
     "telefono": 6635544,
     "fecha_de_nacimiento":"2002-01-10",
     "email": "lkljassss@gmail.com",
     "dni": "25212575s"


    


    

  }
#############muestra un ID####
GET {{host}}{{urlclientes}}/1

##########borra un cliente por id####
DELETE {{host}}{{urlclientes}}/4

############################################
############################################
##############  Api Hoteles  ###############

####devuelve los hoteles####
GET {{host}}{{urlHotel}}

#####inserta un hotel####
POST {{host}}{{urlHotel}}
Content-Type: application/json

  {
    "nombre": "viking",
    "direccion": "nafsdsa 125",
    "ciudad":"noruega",
    "numero_de_estrellas": 5,
    "descripcion":"hotel valhalla",
    "tarifa":"B5"

  }

##########borra un hotel por id#####
DELETE  {{host}}{{urlHotel}}/

###############APIviaje#############
####################################
GET {{host}}{{urlViaje}}
#####


POST {{host}}{{urlViaje}}
Content-Type: application/json

  {
    
    "fecha_salida": "2023-12-02",
    "fecha_vuelta": "2023-12-15",
    "identificador_vuelo_ida":"252ss",
    "identificador_vuelo_vuelta": "545ss",
    "hotel":"Melia"
    

  }

###########
#######

DELETE  {{host}}{{urlViaje}}/6






